sco (Arg Bas Cor Sfe)
    (Mxc Gdl Mex Ver)
    (Col Bog Cli Crt)
    (Brz Bah Rdj Spa)
    (Chl San Tem Val)
    (Per Are Cuz Lim)
    (Spn Hav Pri Sdc)
    (USA Atl Nor Nyc Was)
    (Ven Bol Car Mar)
    (Gbr Hal Jam Mal Mon Tri)
    (UNO Ala Ant Asu Bgu Bis Cal Chi Dgu Eas Ecu Gal Gre Gua Hai Haw
          Lpa Man Mge Nic Ore Pan Pat Scr Sdo Tex Tor Uru Yuc)
