sco (bri Edi Egy Liv Lon)
    (uss Ath Kie Len Mos Sev)
    (fra Bre Buc Mar Par)
    (ger Beo Ber Ham Mun)
    (ita Nap Rom Swe Tri)
    (pol Dan Kra Mad War)
    (tur Ank Con Pra Smy)
    (UNO Aus Bel Bul Den Fin Hol Hun Ire Lit Osl Por Swi Syr Tun)
